### ISSUE TITLE
java_agent default action should be string

### ISSUE THREAD

**Issue by pmacdougall** [djoos-cookbooks/newrelic#267]
Just started getting this error for the java_agent and had to override the`['newrelic']['java_agent']['agent_action']` attribute to be `'install'` to make it work.  Not sure why this suddenly cropped up, I'll try to investigate further when/if I have the time.

```
Generated at 2016-09-23 13:11:48 +0000
Chef::Exceptions::ValidationFailed: Option agent_action must be a kind of String!  You passed :install.
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:157:in `_pv_kind_of'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:70:in `block (2 levels) in validate'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:67:in `each'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:67:in `block in validate'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:57:in `each'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:57:in `validate'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:97:in `set_or_return'
/opt/chef/embedded/apps/chef/lib/chef/resource/lwrp_base.rb:81:in `block in attribute'
/var/chef/cache/cookbooks/newrelic/recipes/java_agent.rb:49:in `block in from_file'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `instance_eval'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource_builder.rb:90:in `build'
/opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:110:in `build_resource'
/opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:71:in `declare_resource'
/opt/chef/embedded/apps/chef/lib/chef/dsl/resources.rb:15:in `newrelic_agent_java'
/var/chef/cache/cookbooks/newrelic/recipes/java_agent.rb:8:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:292:in `block in include_recipe'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `each'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/brighter-newrelic/recipes/elasticsearch.rb:24:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:292:in `block in include_recipe'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `each'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:291:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/brighter-role-elasticsearch-data/recipes/default.rb:8:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:336:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:97:in `load'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:486:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:266:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:55:in `load'
/usr/bin/chef-client:55:in `<main>'
```

**Comment by djoos** [comment]
Hi there,

I've given this a go by additionally adding the agent_action as attribute on the ([existing](https://github.com/djoos-cookbooks/newrelic/blob/master/.kitchen.yml#L31-L42)) java-agent suite locally (ran the test on the [ubuntu-1604-platform with Java 7](https://github.com/djoos-cookbooks/newrelic/blob/master/.kitchen.yml#L31-L42), see .kitchen.yml), ie.

```
  - name: java-agent
    run_list: "recipe[newrelic_lwrp_test::agent_java]"
    attributes:
      newrelic:
        java_agent:
          install_dir: '/opt/tomcat_java_test_app'
          agent_action: :install
```

This seems to work without any problem. I'll close this issue for now, but please do not hesitate to reach out if you are able to reproduce the issue and ping over a test-kitchen suite, so we can take it from there!

Kind regards,
David
