### ISSUE TITLE
Error executing action `install` on resource 'newrelic_agent_infrastructure[Install]' using data bag.

### ISSUE THREAD

**Issue by daniel-rocha-ciandt** [djoos-cookbooks/newrelic#344]
Hello,

We're trying to install New Relic infrastructure agent using a third party cookbook. But we've got an error:     
            Error executing action `install` on resource 'newrelic_agent_infrastructure[Install]'

Our Recipe:
```
#
# Cookbook:: third-party-newrelic
# Recipe:: infraestructure-agent
#
# Copyright:: 2018, The Authors, All Rights Reserved.

include_recipe 'base::databag'
include_recipe 'newrelic::infrastructure_agent'
# Default Variables
newrelic = decrypt_databag('newrelic')

node.normal['newrelic']['license'] = newrelic['license_key']
```

Log Error:

```
Recipe: newrelic::infrastructure_agent
  * newrelic_agent_infrastructure[Install] action install
    
    ================================================================================
    Error executing action `install` on resource 'newrelic_agent_infrastructure[Install]'
    ================================================================================
    
    RuntimeError
    ------------
    The NewRelic key is required.
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/newrelic/libraries/helpers.rb:15:in `check_license'
    /var/chef/cache/cookbooks/newrelic/providers/agent_infrastructure.rb:18:in `block in class_from_file'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/newrelic/recipes/infrastructure_agent.rb
    
      8: newrelic_agent_infrastructure 'Install'
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/newrelic/recipes/infrastructure_agent.rb:8:in `from_file'
    
    newrelic_agent_infrastructure("Install") do
      action [:install]
      default_guard_interpreter :default
      declared_type :newrelic_agent_infrastructure
      cookbook_name "newrelic"
      recipe_name "infrastructure_agent"
    end
    
    System Info:
    ------------
    chef_version=13.8.5
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
    program_name=chef-client worker: ppid=101819;start=19:52:27;
    executable=/opt/chef/bin/chef-client
    

Running handlers:
[2018-05-10T19:52:34+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-05-10T19:52:34+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 07 seconds
[2018-05-10T19:52:34+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-05-10T19:52:34+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-05-10T19:52:34+00:00] ERROR: newrelic_agent_infrastructure[Install] (newrelic::infrastructure_agent line 8) had an error: RuntimeError: The NewRelic key is required.
[2018-05-10T19:52:34+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
Even though using the follow line instead of a data bag:

node.default_unless['newrelic']['license'] = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

We've tried many alternatives for this command, but it wasn't fertile.

Thanks in Advance.

**Comment by djoos** [comment]
Hi @daniel-rocha-ciandt,

thanks for reaching out!

I spot in the _third-party-newrelic_ snippet you posted that the setting of the node attribute is done ***after*** the _newrelic::infrastructure_agent_ is included. At the time of running newrelic::infrastructure_agent, the node attribute will be empty as highlighted by the error that is thrown...

Would you mind having another look at the code and let me know how it goes?

Thanks in advance for your feedback!
David

**Comment by daniel-rocha-ciandt** [comment]
Hi, 

Ok We manage to solve this problem by changing this line in the followed files: 
../resources/agent_infrastructure.rb 
../resources/agent_php.rb

From:

attribute :license, :kind_of => String,  :default => NewRelic.application_monitoring_license(node)

To:

attribute :license, :kind_of => String, :default => lazy { NewRelic.application_monitoring_license(node) }

Inside the recipe

node.default['newrelic']['license'] = newrelic['license_key']

Calling our data bag with this structure:

id:          newrelic
license_key:xxxxxxxxxxxxxxxxxxxxx

Thanks for the tip.
