### ISSUE TITLE
Cloning resource attributes for service[newrelic-daemon] from prior resource

### ISSUE THREAD

**Issue by dipthegeezer** [djoos-cookbooks/newrelic#374]
Hello

I get the following warning when running the recipe

>  "newrelic::php_agent"

`Cloning resource attributes for service[newrelic-daemon] from prior resource
Previous service[newrelic-daemon]: /var/chef/cache/cookbooks/newrelic/providers/agent_php.rb:80:in `newrelic_daemon'
Current  service[newrelic-daemon]: /var/chef/cache/cookbooks/newrelic/providers/agent_php.rb:170:in `startup_mode_config' at 1 location:
    - /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/resource_cloning.rb:58:in `emit_cloned_resource_warning'
   See https://docs.chef.io/deprecations_resource_cloning.html for further details.`

We are currently on chef 12 but will be moving to the latest chef soon and are concerned that the warning will turn into an error

Thank you.

**Comment by lamont-granquist** [comment]
Most 3694 resource cloning errors are ignorable, this is probably one of the ignorable ones.

See:

https://github.com/chef/chef/blob/master/docs/dev/how_to/upgrading_from_chef_12.md#chef-3694-deprecation-warnings
