### ISSUE TITLE
Cookbook failed on chef-client 17.8.25

### ISSUE THREAD

**Issue by mailrahulsre** [djoos-cookbooks/newrelic#398]
ArgumentError
-------------
wrong number of arguments (given 2, expected 1)

Cookbook Trace: (most recent call first)
----------------------------------------
  /root/.chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/option_collector.rb:98:in `option_collector_attribute'
  /root/.chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/option_collector.rb:83:in `attribute'
  /root/.chef/local-mode-cache/cache/cookbooks/poise/files/halite_gem/poise/helpers/template_content.rb:143:in `attribute'
  /root/.chef/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/resources/poise_archive.rb:67:in `<class:Resource>'
  /root/.chef/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/resources/poise_archive.rb:39:in `<module:PoiseArchive>'
  /root/.chef/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/resources/poise_archive.rb:28:in `<module:Resources>'
  /root/.chef/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/resources/poise_archive.rb:25:in `<module:PoiseArchive>'
  /root/.chef/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/resources/poise_archive.rb:24:in `<top (required)>'
  /root/.chef/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/resources.rb:17:in `<top (required)>'
  /root/.chef/local-mode-cache/cache/cookbooks/poise-archive/files/halite_gem/poise_archive/cheftie.rb:17:in `<top (required)>'
  /root/.chef/local-mode-cache/cache/cookbooks/poise-archive/libraries/default.rb:19:in `<top (required)>'

+++++++++++++

I have removed poise-python and then it worked.. Can you please help us release a new version.. Thanks!!

**Comment by scrthq** [comment]
👍 this is very necessary, especially with Chef Infra 18 out in development preview already. Poise is long deprecated and as of 17 no longer works due to the upgrade to Ruby 3.0

**Comment by djoos** [comment]
If you don't make use of the Python side of things of this cookbook, removing the poise-python dependency is a workaround, keeping in mind that the [agent_python](https://github.com/djoos-cookbooks/newrelic/blob/2.12.3/providers/agent_python.rb) provider makes use of poise_python resource(s) and will need refactoring.

Happy for anyone to help out and push me a PR to fast-track the process.

HTH!
